// ─── Image sources ────────────────────────────────────────────────────────────
const CDN = 'https://demo-al-binaa-v3-production.up.railway.app/images';
const LOCAL = '/images';

export const IMGS = {
  // ── Hero & general, real Al Binaa projects in Muscat ──
  hero:         `${LOCAL}/office-1991-night.jpg`,   // OFFICE 1991 tower lit at night
  commercial1:  `${LOCAL}/office-1991.jpg`,          // OFFICE 1991 daytime, structure
  commercial2:  `${LOCAL}/the-office-exterior.jpg`,  // The Office, Al Ghubrah
  residential1: `${LOCAL}/office-1991.jpg`,           // OFFICE 1991, glass & metalwork bespoke finishing detail
  residential2: `${LOCAL}/rimal-1-facade.jpg`,       // Rimal I façade, Bausher
  industrial1:  `${LOCAL}/structure-hero.jpg`,        // Construction cranes at golden hour, structure hero
  mepSystems:   `${LOCAL}/mep-systems.png`,           // MEP piping systems, green, grey & orange pipes
  building1:    `${LOCAL}/office-1991-render.jpg`,   // OFFICE 1991 render, Muscat skyline, Grand Mosque backdrop
  building2:    `${LOCAL}/rimal-1-exterior.jpg`,     // Rimal I street-level exterior

  // ── Completed project photos (from company profile) ──
  alWadiAerial:     `${LOCAL}/al-wadi-complex-aerial.jpg`,
  alWadiCourtyard:  `${LOCAL}/al-wadi-complex-courtyard.jpg`,
  alWadiPool:       `${LOCAL}/al-wadi-complex-pool.jpg`,
  rimal1Aerial:     `${LOCAL}/rimal-1-aerial.jpg`,
  rimal1Facade:     `${LOCAL}/rimal-1-facade.jpg`,
  rimal1Exterior:   `${LOCAL}/rimal-1-exterior.jpg`,
  rimal1Kitchen:    `${LOCAL}/rimal-1-kitchen.jpg`,
  rimal1Living:     `${LOCAL}/rimal-1-living.jpg`,
  officeExterior:   `${LOCAL}/the-office-exterior.jpg`,
  officeGlass:      `${LOCAL}/the-office-glass.jpg`,
  officeInterior:   `${LOCAL}/the-office-interior.jpg`,
  office1991Night:  `${LOCAL}/office-1991-night.jpg`,
  office1991Render: `${LOCAL}/office-1991-render.jpg`,
  dnrVilla:         `${LOCAL}/dnr-villa.jpg`,
  dnrDining:        `${LOCAL}/dnr-dining.jpg`,
  surPlazaLobby:    `${LOCAL}/sur-plaza-lobby.jpg`,
  surPlazaPool:     `${LOCAL}/sur-plaza-pool.jpg`,
  alWadiSoharPool:  `${LOCAL}/al-wadi-hotel-sohar-pool.jpg`,

  // ── Ongoing project renders (concept only) ──
  rimal2Render:          `${LOCAL}/rimal-2-render.jpg`,
  azVillaPool:           `${LOCAL}/az-villa-render-pool.jpg`,
  azVillaExterior:       `${LOCAL}/az-villa.jpg`,
  azVillaAerial:         `${LOCAL}/az-villa-render-aerial.jpg`,
  souqAerial:            `${LOCAL}/souq-hamidiyya-render-aerial.jpg`,
  souqStreet:            `${LOCAL}/souq-hamidiyya-render-street.jpg`,
  ibisRuwiRender:        `${LOCAL}/ibis-ruwi-render.jpg`,
  edgeBuildingRender:    `${LOCAL}/edge-building-render.jpg`,
  alKhuwairRender:       `${LOCAL}/al-khuwair-render.jpg`,
  alHailRender:          `${LOCAL}/al-hail-render.jpg`,
};

// ─── Completed Projects ────────────────────────────────────────────────────
export const COMPLETED_PROJECTS = [
  {
    id: 'rimal-1',
    title: 'Rimal I',
    subtitle: 'Residential Complex',
    client: 'AQAR, Al Khonji Real Estate',
    clientAr: 'عقار، الخنجي للعقارات',
    location: 'Bausher, Muscat',
    locationAr: 'الباطنة، مسقط',
    year: 2015,
    category: 'Residential',
    cost: '13,590,000',
    area: '—',
    img: IMGS.rimal1Exterior,
    imgs: [IMGS.rimal1Aerial, IMGS.rimal1Facade, IMGS.rimal1Exterior, IMGS.rimal1Kitchen, IMGS.rimal1Living],
    desc: '242-unit premium residential landmark, duplex, studio, 1–4 bedroom apartments, a shopping mall, and three underground basement parking levels. A 10-storey development with electronically operated access gates.',
    descAr: 'معلم سكني فاخر من 242 وحدة، شقق دوبلكس واستوديو و1–4 غرف نوم، ومركز تجاري، وثلاثة مستويات من مواقف السيارات تحت الأرض. مشروع من 10 طوابق بأبواب دخول إلكترونية.',
    highlights: ['242 residential units', '10-storey building', '3 basement parking levels', 'Shopping mall included', 'Grand twin reception lobbies'],
  },
  {
    id: 'office-1991',
    title: 'OFFICE 1991',
    subtitle: 'Commercial Tower',
    client: 'AQAR, Al Khonji Real Estate',
    clientAr: 'عقار، الخنجي للعقارات',
    location: 'Bausher, Muscat',
    locationAr: 'الباطنة، مسقط',
    year: 2021,
    category: 'Commercial',
    cost: '12,100,000',
    area: '—',
    img: IMGS.office1991Night,
    imgs: [IMGS.office1991Night, IMGS.office1991Render],
    desc: 'Nine-storey commercial tower in the heart of Muscat\'s commercial district, rising 35 m with four levels of underground parking. Delivered with bespoke high-quality finishes ahead of schedule.',
    descAr: 'برج تجاري من تسعة طوابق في قلب الحي التجاري بمسقط، يرتفع 35 متراً مع أربعة مستويات من مواقف السيارات تحت الأرض. سُلِّم بتشطيبات راقية قبل الموعد المحدد.',
    highlights: ['9 floors above grade', '35 m total height', '4 underground parking levels', 'Bespoke architectural fit-out'],
  },
  {
    id: 'the-office',
    title: 'The Office',
    subtitle: 'Commercial Development',
    client: 'AQAR, Al Khonji Real Estate',
    clientAr: 'عقار، الخنجي للعقارات',
    location: 'Al Ghubrah, Muscat',
    locationAr: 'الغبرة، مسقط',
    year: 2018,
    category: 'Commercial',
    cost: '7,250,000',
    area: '—',
    img: IMGS.officeExterior,
    imgs: [IMGS.officeExterior, IMGS.officeGlass, IMGS.officeInterior],
    desc: 'Modern commercial complex offering 80 flexible office units in a prime Al Ghubrah address, with three levels of underground parking. Built to meet the demands of contemporary Omani businesses.',
    descAr: 'مجمع تجاري حديث يضم 80 وحدة مكتبية مرنة في موقع متميز بالغبرة، مع ثلاثة مستويات من مواقف السيارات تحت الأرض. صُمِّم لتلبية متطلبات الأعمال العُمانية المعاصرة.',
    highlights: ['80 office units', '3 underground parking levels', 'Prime Al Ghubrah location', 'Flexible workspace configurations'],
  },
  {
    id: 'al-wadi-complex',
    title: 'Al Wadi Complex',
    subtitle: 'Residential Townhouses',
    client: 'AQAR, Al Khonji Real Estate',
    clientAr: 'عقار، الخنجي للعقارات',
    location: 'Bausher, Muscat',
    locationAr: 'الباطنة، مسقط',
    year: 2012,
    category: 'Residential',
    cost: '9,450,000',
    area: '21,000 sqm',
    img: IMGS.alWadiAerial,
    imgs: [IMGS.alWadiAerial, IMGS.alWadiCourtyard, IMGS.alWadiPool],
    desc: '21 well-designed townhouses across 21,000 sqm in Bausher. The complex features a swimming pool, children\'s play area, and landscaped outdoor spaces that foster a family-friendly community.',
    descAr: '21 تاون هاوس مصمم بعناية على مساحة 21,000 م² في الباطنة. يتميز المجمع بمسبح ومنطقة لعب للأطفال ومساحات خضراء منسقة تعزز جو الحياة الأسرية.',
    highlights: ['21 townhouses', '21,000 sqm land area', 'Swimming pool & play area', 'Landscaped communal spaces'],
  },
  {
    id: 'desert-nights-resort',
    title: 'Desert Nights Resort',
    subtitle: 'Hospitality Renovation',
    client: 'OHTC',
    clientAr: 'OHTC',
    location: 'Bidyah Sand Dunes',
    locationAr: 'كثبان بدية الرملية',
    year: 2018,
    category: 'Hospitality',
    cost: '2,850,000',
    area: '18,000 sqm',
    img: IMGS.dnrVilla,
    imgs: [IMGS.dnrVilla, IMGS.dnrDining],
    desc: 'Full renovation of a distinguished desert resort set among Bidyah\'s sand dunes. Delivered in a challenging remote environment, enhancing functionality and aesthetic appeal while preserving the resort\'s unique desert character.',
    descAr: 'تجديد كامل لمنتجع صحراوي مميز وسط كثبان بدية الرملية. نُفِّذ في بيئة نائية صعبة مع تعزيز الوظائف والمظهر الجمالي مع الحفاظ على طابع المنتجع الصحراوي الفريد.',
    highlights: ['18,000 sqm total area', 'Remote dune site execution', 'Full renovation & refurbishment', 'Desert character preserved'],
  },
  {
    id: 'al-wadi-hotel-sohar',
    title: 'Al Wadi Hotel Sohar',
    subtitle: 'Hotel Renovation',
    client: 'Oman Hotels',
    clientAr: 'فنادق عُمان',
    location: 'Sohar, Oman',
    locationAr: 'صحار، عُمان',
    year: 2023,
    category: 'Hospitality',
    cost: '600,000',
    area: '32,000 sqm',
    img: IMGS.alWadiSoharPool,
    imgs: [IMGS.alWadiSoharPool],
    desc: 'Full renovation of a 110-room hotel covering 32,000 sqm including guest rooms, commercial spaces, and entertainment areas. Completed to international hospitality standards.',
    descAr: 'تجديد كامل لفندق من 110 غرفة على مساحة 32,000 م² تشمل غرف الضيوف والمساحات التجارية ومناطق الترفيه. أُنجز وفق المعايير الدولية للضيافة.',
    highlights: ['110 guest rooms renovated', '32,000 sqm covered area', 'Commercial & entertainment areas', 'International hospitality standard'],
  },
  {
    id: 'sur-plaza-hotel',
    title: 'Best Western Sur Plaza',
    subtitle: 'Hotel Renovation',
    client: 'Oman Hotels',
    clientAr: 'فنادق عُمان',
    location: 'Sur, Oman',
    locationAr: 'صور، عُمان',
    year: 2023,
    category: 'Hospitality',
    cost: '300,000',
    area: '—',
    img: IMGS.surPlazaPool,
    imgs: [IMGS.surPlazaPool, IMGS.surPlazaLobby],
    desc: 'Targeted renovation of the Best Western Sur Plaza Hotel, upgrading guest-facing spaces and back-of-house systems to raise service quality and meet brand standards.',
    descAr: 'تجديد مستهدف لفندق Best Western Sur Plaza، بتطوير المساحات المواجهة للضيوف والأنظمة الخلفية لرفع جودة الخدمة وتلبية معايير العلامة التجارية.',
    highlights: ['Full brand-standard renovation', 'Guest room & lobby upgrades', 'MEP systems overhaul'],
  },
  {
    id: 'al-qurm-hills',
    title: 'Al Qurm Hills',
    subtitle: 'Premium Townhouses',
    client: 'AQAR, Al Khonji Real Estate',
    clientAr: 'عقار، الخنجي للعقارات',
    location: 'Al Qurm, Muscat',
    locationAr: 'القرم، مسقط',
    year: 2012,
    category: 'Residential',
    cost: '—',
    area: '—',
    img: `${LOCAL}/al-qurm-hills-render.jpg`,
    desc: '13 premium townhouses in Al Qurm with a high level of technical expertise and exceptional premium finishes throughout the structural and fit-out phases.',
    descAr: '13 تاون هاوس فاخراً في القرم بمستوى عالٍ من الخبرة التقنية وتشطيبات استثنائية راقية في مراحل الهيكل والتجهيز.',
    highlights: ['13 premium townhouses', 'Exceptional premium finishes', 'High structural quality'],
  },
  {
    id: 'al-qurm-terrace',
    title: 'Al Qurm Terrace',
    subtitle: 'Premium Townhouses',
    client: 'AQAR, Al Khonji Real Estate',
    clientAr: 'عقار، الخنجي للعقارات',
    location: 'Al Qurm, Muscat',
    locationAr: 'القرم، مسقط',
    year: 2003,
    category: 'Residential',
    cost: '—',
    area: '—',
    img: `${LOCAL}/al-qurm-terrace-render.jpg`,
    desc: '12 townhouses in Al Qurm combining technical expertise with premium architectural finishes, one of Al Binaa\'s earliest landmark residential deliveries.',
    descAr: '12 تاون هاوس في القرم تجمع بين الخبرة التقنية والتشطيبات المعمارية الراقية، أحد أوائل المشاريع السكنية البارزة للبناء.',
    highlights: ['12 townhouses', 'Premium finishes', 'Al Binaa founding-era project'],
  },
];

// ─── Ongoing Projects (concept renders only) ─────────────────────────────
export const ONGOING_PROJECTS = [
  {
    id: 'rimal-2',
    title: 'Rimal II',
    subtitle: 'Residential Complex',
    client: 'AQAR, Al Khonji Real Estate',
    clientAr: 'عقار، الخنجي للعقارات',
    location: 'Bausher, Muscat',
    locationAr: 'الباطنة، مسقط',
    year: 2024,
    category: 'Residential',
    cost: '13,000,000',
    area: '52,000 sqm',
    img: IMGS.rimal2Render,
    imgs: [IMGS.rimal2Render],
    desc: '148 residential units across 52,000 sqm, 1, 2 and 3-bedroom apartments plus a shopping mall in a 10-storey building with three underground parking levels.',
    descAr: '148 وحدة سكنية على مساحة 52,000 م²، شقق بغرفة إلى 3 غرف نوم ومركز تجاري في مبنى من 10 طوابق مع ثلاثة مستويات مواقف سيارات تحت الأرض.',
    highlights: ['148 residential units', '52,000 sqm total area', '10-storey with 3B parking', 'Integrated shopping mall'],
  },
  {
    id: 'ibis-ruwi',
    title: 'Ibis Style Hotel, Ruwi',
    subtitle: 'Hotel Renovation',
    client: 'Oman Hotels',
    clientAr: 'فنادق عُمان',
    location: 'Ruwi, Muscat',
    locationAr: 'الروي، مسقط',
    year: 2025,
    category: 'Hospitality',
    cost: '5,200,000',
    area: '42,000 sqm',
    img: IMGS.ibisRuwiRender,
    imgs: [IMGS.ibisRuwiRender],
    desc: '183-room hotel renovation covering 42,000 sqm of guest rooms, common areas, and entertainment facilities to Ibis Style brand standards.',
    descAr: 'تجديد فندق من 183 غرفة على مساحة 42,000 م² تشمل غرف الضيوف والمناطق المشتركة ومرافق الترفيه وفق معايير علامة Ibis Style.',
    highlights: ['183 guest rooms', '42,000 sqm total scope', 'Common & entertainment areas', 'International brand standards'],
  },
  {
    id: 'edge-building',
    title: 'The Edge Building',
    subtitle: 'Commercial Development',
    client: 'Al Khonji Group',
    clientAr: 'مجموعة الخنجي',
    location: 'Al Hamryia, Muscat',
    locationAr: 'الحمرية، مسقط',
    year: 2025,
    category: 'Commercial',
    cost: '3,100,000',
    area: '—',
    img: IMGS.edgeBuildingRender,
    imgs: [IMGS.edgeBuildingRender],
    desc: 'Multi-use commercial building in Al Hamryia under active construction. Tile works, painting, ceiling works, and external finishes currently in progress.',
    descAr: 'مبنى تجاري متعدد الاستخدامات في الحمرية قيد الإنشاء. أعمال البلاط والطلاء والأسقف والتشطيبات الخارجية جارية حالياً.',
    highlights: ['Structure & blockwork complete', 'Tile & ceiling works ongoing', 'Painting in progress', 'External works ongoing'],
  },
  {
    id: 'souq-hamidiya',
    title: 'Souq Al Hamidiyya',
    subtitle: 'Commercial Retail',
    client: 'Al Khonji Group',
    clientAr: 'مجموعة الخنجي',
    location: 'Al Seeb, Muscat',
    locationAr: 'السيب، مسقط',
    year: 2025,
    category: 'Commercial',
    cost: '2,100,000',
    area: '18,000 sqm',
    img: IMGS.souqAerial,
    imgs: [IMGS.souqAerial, IMGS.souqStreet],
    desc: '190-unit commercial souq across 18,000 sqm in Al Seeb. Piling works complete; foundation works currently in progress.',
    descAr: 'سوق تجاري من 190 وحدة على مساحة 18,000 م² في السيب. أعمال الخوازيق مكتملة وأعمال الأساسات جارية.',
    highlights: ['190 commercial shops', '18,000 sqm land area', 'Piling complete', 'Foundation in progress'],
  },
  {
    id: 'al-khuwair-building',
    title: 'Al Khuwair Building',
    subtitle: 'Commercial Development',
    client: 'Al Khonji Group',
    clientAr: 'مجموعة الخنجي',
    location: 'Al Khuwair, Muscat',
    locationAr: 'الخوير، مسقط',
    year: 2025,
    category: 'Commercial',
    cost: '2,500,000',
    area: '—',
    img: IMGS.alKhuwairRender,
    imgs: [IMGS.alKhuwairRender],
    desc: 'Commercial building under construction in the established Al Khuwair business district.',
    descAr: 'مبنى تجاري قيد الإنشاء في حي الخوير التجاري الراسخ.',
    highlights: ['Prime Al Khuwair location', 'Under active construction'],
  },
  {
    id: 'az-villa',
    title: 'AZ Villa',
    subtitle: 'Private Luxury Villa',
    client: 'Private Client',
    clientAr: 'عميل خاص',
    location: 'Muscat',
    locationAr: 'مسقط',
    year: 2025,
    category: 'Private Villas',
    cost: '645,000',
    area: '1,100 sqm',
    img: IMGS.azVillaExterior,
    imgs: [IMGS.azVillaPool, IMGS.azVillaExterior, IMGS.azVillaAerial],
    desc: 'Luxury private villa of 1,100 sqm currently under construction in Muscat, combining modern design with premium materials and bespoke finishes.',
    descAr: 'فيلا خاصة فاخرة بمساحة 1,100 م² قيد الإنشاء في مسقط، تجمع بين التصميم العصري والمواد الراقية والتشطيبات المخصصة.',
    highlights: ['1,100 sqm built area', 'Luxury & modern design', 'Bespoke premium finishes'],
  },
  {
    id: 'al-hail-building',
    title: 'Al Hail Building',
    subtitle: 'Residential + Commercial',
    client: 'Al Khonji Group',
    clientAr: 'مجموعة الخنجي',
    location: 'Al Hail, Muscat',
    locationAr: 'الحيل، مسقط',
    year: 2025,
    category: 'Residential',
    cost: '500,000',
    area: '—',
    img: IMGS.alHailRender,
    imgs: [IMGS.alHailRender],
    desc: '16-apartment residential building with ground-floor commercial spaces under construction in Al Hail.',
    descAr: 'مبنى سكني من 16 شقة مع مساحات تجارية في الطابق الأرضي قيد الإنشاء في الحيل.',
    highlights: ['16 residential apartments', 'Ground-floor commercial units', 'Mixed-use development'],
  },
];

// ─── Services ─────────────────────────────────────────────────────────────
export const SERVICES = [
  {
    num: '01',
    key: 'structure',
    title: 'Structure',
    titleAr: 'الهيكل الإنشائي',
    img: IMGS.industrial1,
    tagline: 'Reinforced concrete & steel, from single villa to 13-storey tower',
    taglineAr: 'الخرسانة المسلحة والصلب، من الفيلا إلى البرج المكوّن من 13 طابقاً',
    desc: 'Our structural division delivers robust, precision-engineered concrete and steel frameworks for projects of every scale, from private villas to 13-storey mixed-use towers. We manage every phase from substructure to superstructure.',
    descAr: 'يقدم قسمنا الإنشائي هياكل خرسانية وفولاذية متينة ومهندسة بدقة لمشاريع من جميع الأحجام، من الفلل الخاصة إلى الأبراج متعددة الاستخدامات المكوّنة من 13 طابقاً. ندير كل مرحلة من البنية التحتية إلى الهيكل العلوي.',
    scope: [
      'Reinforced concrete design & execution',
      'Deep foundations, piling & raft',
      'Post-tensioned slabs & transfer structures',
      'Structural steel fabrication & erection',
      'Basement & below-grade construction',
      'Surveying, setting-out & quality control',
    ],
    scopeAr: [
      'تصميم وتنفيذ الخرسانة المسلحة',
      'الأساسات العميقة، الركائز والطوافات',
      'الألواح المشدودة لاحقاً وهياكل النقل',
      'تصنيع الصلب الإنشائي وتركيبه',
      'البناء تحت مستوى الأرض',
      'المسح والترقيم ومراقبة الجودة',
    ],
  },
  {
    num: '02',
    key: 'mep',
    title: 'MEP',
    titleAr: 'الميكانيكا والكهرباء والسباكة',
    img: IMGS.mepSystems,
    tagline: 'Mechanical, Electrical & Plumbing, designed and installed in-house',
    taglineAr: 'الميكانيكا والكهرباء والسباكة، تصميم وتنفيذ داخلي متكامل',
    desc: 'Al Binaa\'s MEP division provides full mechanical, electrical, and plumbing systems designed and installed to Oman authority standards. Our in-house engineers co-ordinate all disciplines from design stage through commissioning.',
    descAr: 'يوفر قسم MEP في البناء أنظمة ميكانيكية وكهربائية وسباكة متكاملة مصممة ومنفذة وفق معايير السلطات العُمانية. ينسق مهندسونا الداخليون جميع التخصصات من مرحلة التصميم حتى التشغيل.',
    scope: [
      'HVAC design, supply & installation',
      'Low-voltage electrical systems',
      'Plumbing, drainage & fire-fighting',
      'BMS / smart building systems',
      'Solar & energy-efficient systems',
      'Testing, commissioning & handover',
    ],
    scopeAr: [
      'تصميم وتوريد وتركيب أنظمة التكييف',
      'أنظمة الكهرباء منخفضة الجهد',
      'السباكة والصرف الصحي وإطفاء الحريق',
      'أنظمة إدارة المبنى الذكية',
      'الأنظمة الشمسية وكفاءة الطاقة',
      'الاختبار والتشغيل والتسليم',
    ],
  },
  {
    num: '03',
    key: 'finishing',
    title: 'Interior Finishing & Quality',
    titleAr: 'التشطيبات الداخلية والجودة',
    img: IMGS.residential1,
    tagline: 'The quality layer clients see every day: plaster, tile, gypsum, paint',
    taglineAr: 'طبقة الجودة التي يعيشها العميل يومياً: لياسة وبلاط وجبس وطلاء',
    desc: 'Our finishing division is responsible for the final layer of quality that clients and end-users experience every day. Skilled tradespeople across plastering, tiling, gypsum, painting, and decoration bring specifications to life.',
    descAr: 'قسم التشطيبات لدينا مسؤول عن الطبقة الأخيرة من الجودة التي يعايشها العملاء والمستخدمون كل يوم. حرفيون مهرة في اللياسة والبلاط والجبس والطلاء والديكور يحولون المواصفات إلى واقع.',
    scope: [
      'Block work, plaster & screeds',
      'Floor & wall tile installation',
      'Gypsum board ceilings & partitions',
      'Decorative painting & feature finishes',
      'Joinery, doors & built-in furniture',
      'External paving, boulders & landscaping',
    ],
    scopeAr: [
      'أعمال البلوك واللياسة والملاط',
      'تركيب بلاط الأرضيات والجدران',
      'أسقف وتقسيمات الجبس بورد',
      'الطلاء الديكوري والتشطيبات المميزة',
      'أعمال النجارة والأبواب والأثاث المدمج',
      'الرصف الخارجي والتنسيق الطبيعي',
    ],
  },
];

// ─── Company History Timeline ─────────────────────────────────────────────
export const HISTORY_TIMELINE = [
  {
    year: '1999',
    milestone: 'Founded',
    milestoneAr: 'التأسيس',
    desc: 'Al Binaa Construction & Industry SAOC established under the Al Khonji Group, Muscat. First project delivered: residential buildings in Muscat.',
    descAr: 'تأسست شركة البناء للمقاولات والصناعة تحت مجموعة الخنجي في مسقط. تسليم أول مشروع: مباني سكنية في مسقط.',
  },
  {
    year: '2003',
    milestone: 'Early Growth',
    milestoneAr: 'النمو المبكر',
    desc: 'Residential building in Darsait, 4 floors, 14 apartments. Al Qurm Terrace delivered: 12 premium townhouses recognised for exceptional finishes.',
    descAr: 'مبنى سكني في درسيت، 4 طوابق و14 شقة. تسليم تراس القرم: 12 تاون هاوس فاخراً مميزاً بتشطيبات استثنائية.',
  },
  {
    year: '2005',
    milestone: 'Villa Portfolio',
    milestoneAr: 'محفظة الفلل',
    desc: '13 Grade A residential villas delivered, establishing Al Binaa’s reputation for premium residential quality.',
    descAr: 'تسليم 13 فيلا سكنية من الدرجة الأولى، ترسيخ سمعة البناء في جودة السكن الفاخر.',
  },
  {
    year: '2012',
    milestone: 'Scale-Up',
    milestoneAr: 'توسع المقياس',
    desc: 'Al Wadi Complex: 21 townhouses across 21,000 sqm. Al Qurm Hills: 13 premium townhouses. Both delivered on schedule to AQAR.',
    descAr: 'مجمع الوادي: 21 تاون هاوس على مساحة 21,000 م². تلال القرم: 13 تاون هاوس فاخراً. تم تسليم كلا المشروعين في الموعد لعقار.',
  },
  {
    year: '2015',
    milestone: 'Landmark, Rimal I',
    milestoneAr: 'معلم رئيسي، ريمال I',
    desc: 'Rimal I completed: 242-unit mixed-use residential tower in Bausher, 10 storeys, 3 basement levels, shopping mall. OMR 13.59M.',
    descAr: 'اكتمال ريمال I: برج سكني متعدد الاستخدامات من 242 وحدة في الباطنة، 10 طوابق و3 مستويات تحت الأرض ومركز تجاري. 13.59 مليون ريال.',
  },
  {
    year: '2018',
    milestone: 'Commercial & Hospitality',
    milestoneAr: 'التجاري والضيافة',
    desc: 'The Office Al Ghubrah: 80 office units, 3B parking (OMR 7.25M). Desert Nights Resort renovation: 18,000 sqm in remote Bidyah dunes (OMR 2.85M).',
    descAr: 'مكاتب الغبرة: 80 وحدة مكتبية و3 مستويات تحت الأرض (7.25م ريال). تجديد منتجع ليالي الصحراء: 18,000 م² في كثبان بدية النائية (2.85م ريال).',
  },
  {
    year: '2021',
    milestone: 'OFFICE 1991',
    milestoneAr: 'أوفيس 1991',
    desc: 'OFFICE 1991 delivered ahead of schedule, 9-storey commercial tower, 4 basement levels, bespoke architectural fit-out. OMR 12.1M.',
    descAr: 'تسليم أوفيس 1991 قبل الموعد المحدد، برج تجاري من 9 طوابق و4 مستويات تحت الأرض وتجهيز معماري مخصص. 12.1 مليون ريال.',
  },
  {
    year: '2023',
    milestone: 'Hospitality Portfolio',
    milestoneAr: 'محفظة الضيافة',
    desc: 'Best Western Sur Plaza Hotel renovation. Al Wadi Hotel Sohar: 110-room full renovation across 32,000 sqm. Both for Oman Hotels.',
    descAr: 'تجديد فندق Best Western Sur Plaza. فندق الوادي صحار: تجديد كامل لـ 110 غرفة على مساحة 32,000 م². كلاهما لفنادق عُمان.',
  },
  {
    year: '2024–25',
    milestone: 'Active Pipeline',
    milestoneAr: 'مشاريع جارية',
    desc: 'Rimal II (148 units, OMR 13M), Ibis Style Hotel Ruwi (183 rooms, OMR 5.2M), Souq Al Hamidiyya (190 shops), The Edge, Al Khuwair, Al Hail Buildings.',
    descAr: 'ريمال II (148 وحدة، 13م ريال)، فندق إيبيس ستايل الروي (183 غرفة، 5.2م ريال)، سوق الحميدية (190 محل)، مبنى ذا إيدج والخوير والحيل.',
  },
];

// ─── Why Choose Us ────────────────────────────────────────────────────────
export const WHY_CHOOSE_US = [
  {
    num: '01',
    title: 'Proven Project Delivery',
    titleAr: 'سجل تسليم مُثبت',
    desc: 'Consistent track record of delivering residential, commercial, and industrial projects on time, within budget, and to specification.',
    descAr: 'سجل حافل بتسليم المشاريع السكنية والتجارية والصناعية في الوقت المحدد وضمن الميزانية وحسب المواصفات.',
  },
  {
    num: '02',
    title: 'End-to-End Capability',
    titleAr: 'قدرة متكاملة من الألف إلى الياء',
    desc: 'Full-scope execution covering structural works, MEP coordination, finishing, and handover, seamless integration across all phases under one contract.',
    descAr: 'تنفيذ شامل يغطي أعمال الهيكل الإنشائي وتنسيق MEP والتشطيبات والتسليم، تكامل سلس عبر جميع المراحل تحت عقد واحد.',
  },
  {
    num: '03',
    title: 'Engineering Expertise',
    titleAr: 'خبرة هندسية عميقة',
    desc: 'Experienced engineers and skilled technical teams applying best practices, modern construction methods, and efficient resource management on every site.',
    descAr: 'مهندسون ذوو خبرة وفرق تقنية ماهرة تطبق أفضل الممارسات وأساليب البناء الحديثة وإدارة الموارد الفعّالة في كل موقع.',
  },
  {
    num: '04',
    title: 'Quality Assurance',
    titleAr: 'ضمان الجودة',
    desc: 'Strict QA/QC procedures aligned with international standards and local authority regulations to guarantee durability, functionality, and long-term performance.',
    descAr: 'إجراءات صارمة لضمان الجودة تتوافق مع المعايير الدولية واللوائح المحلية لضمان المتانة والوظيفية والأداء على المدى البعيد.',
  },
  {
    num: '05',
    title: 'Modern Construction Methods',
    titleAr: 'أساليب بناء حديثة',
    desc: 'Adoption of modern technologies and construction techniques to improve productivity, accuracy, and overall project outcomes.',
    descAr: 'تبني التقنيات الحديثة وأساليب البناء المتطورة لتحسين الإنتاجية والدقة والنتائج الإجمالية للمشروع.',
  },
  {
    num: '06',
    title: 'Client-Centric Approach',
    titleAr: 'نهج يضع العميل في المركز',
    desc: 'Clear communication, responsiveness, and flexibility to meet client requirements and navigate project-specific challenges effectively.',
    descAr: 'تواصل واضح واستجابة ومرونة لتلبية متطلبات العميل والتعامل مع تحديات المشروع الخاصة بفاعلية.',
  },
  {
    num: '07',
    title: 'Reliability & Long-Term Value',
    titleAr: 'الموثوقية والقيمة طويلة الأمد',
    desc: 'Focus on delivering sustainable, high-quality assets that ensure long-term operational performance and client satisfaction across every project.',
    descAr: 'التركيز على تسليم أصول مستدامة عالية الجودة تضمن الأداء التشغيلي طويل الأمد ورضا العملاء في كل مشروع.',
  },
];

// ─── Appreciation Letters ─────────────────────────────────────────────────
export const TESTIMONIALS = [
  {
    quote: 'The speed of execution was remarkable. To deliver a project of this technical nature ahead of expectations, while maintaining such high-quality standards, is a rare achievement in the industry.',
    project: 'OFFICE 1991',
    author: 'Mohamed Al Khonji',
    title: 'Chairman & CEO',
    company: 'Al Khonji Real Estate & Development LLC',
    year: 2021,
  },
  {
    quote: 'Your dedication and commitment to excellence have not gone unnoticed. The professionalism you and your team demonstrated throughout the project lifecycle was critical to its success. Thank you for your impeccable service.',
    project: 'Best Western Sur Plaza',
    author: 'Fred Vessali',
    title: 'CEO',
    company: 'Oman Hotels and Tourism Company SAOC',
    year: 2024,
  },
  {
    quote: 'We truly appreciate your efforts and commitment throughout the Al Wadi Hotel renovation. Your devotion and hard work have been critical to our success, and we look forward to the same level of dedication on the Ibis Styles Hotel, Ruwi.',
    project: 'Al Wadi Hotel Sohar',
    author: 'Fariborz (Fred) Vessali',
    title: 'CEO',
    company: 'Oman Hotels and Tourism Company SAOC',
    year: 2024,
  },
  {
    quote: 'The delivery of 242 residential units is a significant undertaking, and we are thoroughly impressed by the high standard of craftsmanship and the meticulous attention to detail evident in the finishes.',
    project: 'Rimal I',
    author: 'Mohamed Al Khonji',
    title: 'Chairman & CEO',
    company: 'Al Khonji Real Estate & Development LLC',
    year: 2013,
  },
  {
    quote: 'Attention to detail, timeliness, and adherence to site safety protocols throughout the construction phase were all exemplary. Al Binaa Construction has delivered results that truly stand out.',
    project: 'Al Wadi Complex',
    author: 'Mohamed Al Khonji',
    title: 'Chairman & CEO',
    company: 'Al Khonji Real Estate & Development LLC',
    year: 2012,
  },
  {
    quote: 'The development of these 13 townhouses required a high level of technical expertise and attention to detail, and Al Binaa Construction has delivered results that truly stand out. In an industry where timelines and quality often conflict, your team\'s ability to balance both while adhering to safety protocols is commendable.',
    project: 'Al Qurm Hills',
    author: 'Mohamed Al Khonji',
    title: 'Chairman & CEO',
    company: 'Al Khonji Real Estate & Development LLC',
    year: 2012,
  },
  {
    quote: 'The high-quality standards maintained throughout the structural phase and the exceptional premium finishes define the character of these residences. The professionalism shown by your site engineers and project managers played a vital role in bringing this vision to life.',
    project: 'Al Qurm Terrace',
    author: 'Mohamed Al Khonji',
    title: 'Chairman & CEO',
    company: 'Al Khonji Real Estate & Development LLC',
    year: 2003,
  },
];

// ─── Manpower ─────────────────────────────────────────────────────────────
export const MANPOWER = [
  { role: 'Civil Engineers', qty: 15 },
  { role: 'MEP Engineers', qty: 6 },
  { role: 'Drafting Engineers', qty: 3 },
  { role: 'QS Engineers', qty: 1 },
  { role: 'Civil Supervisors', qty: 10 },
  { role: 'MEP Supervisors', qty: 5 },
  { role: 'Finishing Supervisors', qty: 5 },
  { role: 'Surveyors', qty: 4 },
  { role: 'Carpenters (Shuttering)', qty: 40 },
  { role: 'Steel Fixers', qty: 42 },
  { role: 'Masons (Tile Work)', qty: 15 },
  { role: 'Masons (Block Work)', qty: 10 },
  { role: 'Electricians', qty: 18 },
  { role: 'Plumbers', qty: 20 },
  { role: 'Common Labour', qty: 40 },
];

// ─── Equipment ────────────────────────────────────────────────────────────
export const EQUIPMENT = [
  { name: 'Tower Cranes', qty: 6, desc: 'High-capacity vertical lifting for large-scale projects' },
  { name: 'Mobile Cranes', qty: 4, desc: 'Rapid deployment across diverse terrain' },
  { name: 'Heavy Transport Trucks', qty: 5, desc: 'Sand, aggregate, and materials logistics' },
  { name: 'Wheel Loaders', qty: 1, desc: 'Site material handling' },
  { name: 'Bobcats', qty: 2, desc: 'Compact site manoeuvring' },
  { name: 'Doka Formwork', qty: null, desc: '5,900 sqm of heavy-duty formwork' },
  { name: 'Heavy Duty Scaffolding', qty: null, desc: '15,000 sqm capacity' },
  { name: 'Concrete Vibrators', qty: 10, desc: 'Pour quality assurance' },
  { name: 'Survey Equipment', qty: 2, desc: 'Total station & GPS setting-out' },
];

// ─── Nav mega-menu ────────────────────────────────────────────────────────
export const MEGA_MENUS = {
  services: {
    img: IMGS.building2,    // Rimal I exterior, landmark Muscat project
    items: [
      { title: 'Structure',                   desc: 'Reinforced concrete, foundations & steel',   href: '/services', section: 0 },
      { title: 'MEP',                         desc: 'Mechanical, electrical & plumbing systems',  href: '/services', section: 1 },
      { title: 'Interior Finishing & Quality',desc: 'Tiling, gypsum, painting & decoration',     href: '/services', section: 2 },
    ],
  },
  projects: {
    img: IMGS.rimal1Facade,  // default, Rimal I façade
    items: [
      { title: 'Rimal I',                 desc: 'Residential · 242 units · Bausher',       href: '/projects', filter: 'Residential', img: IMGS.rimal1Facade      },
      { title: 'OFFICE 1991',             desc: 'Commercial · 9 floors · Bausher',          href: '/projects', filter: 'Commercial',  img: IMGS.office1991Night   },
      { title: 'Desert Nights Resort',    desc: 'Hospitality · Bidyah sand dunes',          href: '/projects', filter: 'Hospitality', img: IMGS.dnrVilla          },
      { title: 'Rimal II',                desc: 'Ongoing · 148 units · Bausher',            href: '/projects', filter: 'Ongoing',     img: IMGS.rimal2Render      },
    ],
    cta: 'View All Projects',
  },
};

// ─── FAQ (AEO/GEO) ──────────────────────────────────────────────────────────
// Answer-first, self-contained Q&A. Drives both the visible FAQ blocks and the
// FAQPage JSON-LD so answer engines and LLMs can extract clean, citable answers.
export const HOME_FAQ_EN = [
  {
    q: 'How long has Al Binaa been operating in Oman?',
    a: 'Al Binaa Construction & Industry SAOC has operated in Oman since 1997, over 30 years, delivering 200+ projects across residential, commercial, hospitality, health, and industrial sectors. It is part of the Al Khonji Group, one of Oman\'s most established business families.',
  },
  {
    q: 'What does single-contract construction mean?',
    a: 'Single-contract construction means one company delivers structure, MEP, and interior finishing with its own in-house team under one contract. There are no handovers between subcontractors, so the client gets one point of accountability and no coordination or interface risk.',
  },
  {
    q: 'What types of projects does Al Binaa build?',
    a: 'Al Binaa builds residential towers, commercial buildings, hotels, private villas, and renovations, from single villas to 13-storey towers. Typical contract values range from OMR 1M to OMR 20M+, and the company usually runs four to six projects at once.',
  },
  {
    q: 'Is Al Binaa a certified contractor?',
    a: 'Yes. Al Binaa holds ISO 9001:2015 certification from Bureau Veritas and Commercial Registration 2693300 with Oman\'s Ministry of Commerce, Industry and Investment Promotion. QA/QC engineers are assigned on-site from groundwork through final finishing sign-off.',
  },
  {
    q: 'How quickly does Al Binaa respond to enquiries?',
    a: 'Every enquiry is reviewed by a senior project manager, and you receive a detailed response, including preliminary scope and an indicative timeline, within 48 hours.',
  },
  {
    q: 'Where in Oman does Al Binaa work?',
    a: 'Al Binaa is based in Muscat and delivers projects across all governorates of Oman, from Dhofar to the Batinah Coast, and is equipped for full mobilisation anywhere in the Sultanate.',
  },
];
export const HOME_FAQ_AR = [
  {
    q: 'منذ متى تعمل شركة البناء في عُمان؟',
    a: 'تعمل شركة البناء للإنشاءات والصناعة ش.م.ع.م في عُمان منذ عام 1997، أكثر من 30 عاماً، وقد أنجزت أكثر من 200 مشروع في القطاعات السكنية والتجارية والضيافة والصحية والصناعية. وهي جزء من مجموعة الخنجي، إحدى أعرق العائلات التجارية في عُمان.',
  },
  {
    q: 'ماذا يعني نموذج العقد الواحد في الإنشاء؟',
    a: 'يعني نموذج العقد الواحد أن شركة واحدة تنفّذ الهيكل الإنشائي وأنظمة MEP والتشطيبات الداخلية بفريقها الداخلي ضمن عقد واحد. لا تسليم بين مقاولين من الباطن، فيحصل العميل على جهة مسؤولية واحدة دون فجوات تنسيق أو مخاطر تداخل.',
  },
  {
    q: 'ما أنواع المشاريع التي تنفّذها شركة البناء؟',
    a: 'تنفّذ شركة البناء أبراجاً سكنية ومباني تجارية وفنادق وفللاً خاصة وأعمال تجديد، من الفيلا الواحدة إلى الأبراج المكوّنة من 13 طابقاً. تتراوح قيم العقود عادةً بين 1 و20 مليون ريال عُماني وأكثر، وتدير الشركة من أربعة إلى ستة مشاريع في آن واحد.',
  },
  {
    q: 'هل شركة البناء مقاول معتمد؟',
    a: 'نعم. تحمل شركة البناء شهادة ISO 9001:2015 من Bureau Veritas والسجل التجاري 2693300 لدى وزارة التجارة والصناعة وترويج الاستثمار. يُعيَّن مهندسو ضمان الجودة في الموقع من أعمال الأساس حتى التوقيع النهائي على التشطيبات.',
  },
  {
    q: 'ما سرعة رد شركة البناء على الاستفسارات؟',
    a: 'يُراجَع كل استفسار من قِبل مدير مشروع أول، وتتلقى رداً مفصلاً، يشمل النطاق الأولي والجدول الزمني التقديري، خلال 48 ساعة.',
  },
  {
    q: 'أين تعمل شركة البناء في عُمان؟',
    a: 'تتخذ شركة البناء من مسقط مقراً لها وتنفّذ مشاريع في جميع محافظات عُمان، من ظفار إلى ساحل الباطنة، وهي مجهزة للتعبئة الكاملة في أي مكان في السلطنة.',
  },
];

// Process steps (HowTo), mirrors the "From Brief to Handover" section on the homepage.
export const PROCESS_STEPS_EN = [
  { name: 'Brief & Site Assessment', text: 'We visit the site, assess scope, and align on requirements before a drawing is made.' },
  { name: 'Design & Permits', text: 'Our in-house engineers produce permit-ready drawings and manage all authority submissions.' },
  { name: 'Build', text: 'Our three divisions, Structure, MEP, and Finishing, work under one site team.' },
  { name: 'Handover', text: 'Snagging, commissioning, and final quality inspection before keys are handed over.' },
];

// Per-service FAQ for the /services/[slug] pages.
export const SERVICE_FAQ: Record<string, { en: { q: string; a: string }[]; ar: { q: string; a: string }[] }> = {
  structure: {
    en: [
      { q: 'Does Al Binaa handle structural and civil works in-house?', a: 'Yes. Al Binaa\'s structural division delivers reinforced concrete, deep foundations, post-tensioned slabs, and steel framework with directly employed engineers and tradespeople, no agency labour, from single villas to 13-storey towers.' },
      { q: 'What is the tallest structure Al Binaa builds?', a: 'Al Binaa builds from single private villas up to 13-storey mixed-use towers, managing every phase from substructure to superstructure under one contract.' },
    ],
    ar: [
      { q: 'هل تنفّذ شركة البناء أعمال الهيكل الإنشائي والمدني داخلياً؟', a: 'نعم. ينفّذ قسم الهيكل الإنشائي في شركة البناء الخرسانة المسلحة والأساسات العميقة والألواح المشدودة لاحقاً والهياكل الفولاذية بمهندسين وحرفيين موظفين مباشرةً، لا عمالة وكالات، من الفيلا الواحدة إلى الأبراج المكوّنة من 13 طابقاً.' },
      { q: 'ما أعلى هيكل تنفّذه شركة البناء؟', a: 'تنفّذ شركة البناء من الفلل الخاصة المفردة حتى الأبراج متعددة الاستخدامات المكوّنة من 13 طابقاً، وتدير كل مرحلة من البنية التحتية إلى الهيكل العلوي ضمن عقد واحد.' },
    ],
  },
  mep: {
    en: [
      { q: 'Does Al Binaa do MEP in-house?', a: 'Yes. Al Binaa\'s MEP division designs and installs mechanical, electrical, and plumbing systems with in-house engineers, coordinated with structure and finishing under one contract and built to Oman authority standards.' },
      { q: 'What MEP systems does Al Binaa install?', a: 'HVAC, low-voltage electrical, plumbing, drainage, fire-fighting, BMS smart-building systems, and solar, all designed, installed, tested, and commissioned by Al Binaa\'s own team.' },
    ],
    ar: [
      { q: 'هل تنفّذ شركة البناء أنظمة MEP داخلياً؟', a: 'نعم. يصمّم قسم MEP في شركة البناء وينفّذ الأنظمة الميكانيكية والكهربائية والسباكة بمهندسين داخليين، بالتنسيق مع الهيكل والتشطيبات ضمن عقد واحد ووفق معايير السلطات العُمانية.' },
      { q: 'ما أنظمة MEP التي تنفّذها شركة البناء؟', a: 'التكييف والأنظمة الكهربائية منخفضة الجهد والسباكة والصرف الصحي وإطفاء الحريق وأنظمة إدارة المبنى الذكية والطاقة الشمسية، يصممها وينفّذها ويختبرها ويشغّلها فريق شركة البناء.' },
    ],
  },
  finishing: {
    en: [
      { q: 'What does Al Binaa\'s interior finishing cover?', a: 'Al Binaa\'s finishing division delivers plastering, floor and wall tiling, gypsum ceilings and partitions, decorative painting, joinery, and external paving, the final quality layer clients experience every day.' },
      { q: 'Can Al Binaa do finishing only, or as part of a full contract?', a: 'Both. Interior finishing is available as a standalone package or as part of Al Binaa\'s single-contract model alongside structure and MEP.' },
    ],
    ar: [
      { q: 'ماذا تشمل التشطيبات الداخلية لدى شركة البناء؟', a: 'ينفّذ قسم التشطيبات في شركة البناء أعمال اللياسة وبلاط الأرضيات والجدران وأسقف وتقسيمات الجبس والطلاء الديكوري والنجارة والرصف الخارجي، طبقة الجودة الأخيرة التي يعيشها العملاء كل يوم.' },
      { q: 'هل يمكن تنفيذ التشطيبات وحدها أم ضمن عقد متكامل؟', a: 'كلاهما. تتوفر التشطيبات الداخلية كحزمة مستقلة أو ضمن نموذج العقد الواحد لدى شركة البناء إلى جانب الهيكل وأنظمة MEP.' },
    ],
  },
};
